---
- name: Download rabbitmq public key
  get_url: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc dest=/tmp validate_certs=no

- name: Install rabbitmq public key
  apt_key: file=/tmp/rabbitmq-signing-key-public.asc

- name: Adding rabbitmq repo
  lineinfile: dest=/etc/apt/sources.list line="deb https://www.rabbitmq.com/debian/ testing main"

- name: Update apt repos
  apt: update_cache=yes

- name: Install rabbitmq
  apt: name=rabbitmq-server state=present
  notify: enable-rabbitmq
  notify: start-rabbitmq

- name: Add rabbitmq vhost via rabbitmq extra module
  rabbitmq_vhost: name=/sensu state=present

- name: Add rabbitmq user via rabbitmq extra module
  rabbitmq_user: user=sensu
                 password=secret
                 vhost=/sensu
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
  
- name: Cleanup rabbitmq downloads
  file: path=/tmp/rabbitmq-signing-key-public.asc state=absent
