---
- name: Download rabbitmq public key
  get_url: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc dest=/tmp validate_certs=no

- name: Install rabbitmq public key
  apt_key: file=/tmp/rabbitmq-signing-key-public.asc

- name: Adding rabbitmq repo
  lineinfile: dest=/etc/apt/sources.list line="deb https://www.rabbitmq.com/debian/ testing main"

- name: Update apt repos
  apt: update_cache=yes

- name: Install rabbitmq
  apt: name=rabbitmq-server state=present
